# Generated by Django 3.1.7 on 2021-03-16 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselorRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.ImageField(upload_to='media/identification', verbose_name='本人確認書類')),
                ('credentials', models.ImageField(upload_to='media/credentials', verbose_name='資格証明書')),
                ('signature', models.CharField(max_length=20, verbose_name='署名')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('agreement', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
