# Generated by Django 3.1.7 on 2021-03-17 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_counselorregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, choices=[('1', '会社員'), ('2', '専業主婦（夫）'), ('3', '個人事業主・自由業'), ('4', '経営者・役員'), ('5', '学生'), ('6', 'フリーター'), ('7', '無職')], max_length=10, verbose_name='ご職業'),
        ),
        migrations.AlterField(
            model_name='counselorregister',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
