# Generated by Django 3.1.7 on 2021-03-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210309_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Twitter',
            field=models.URLField(blank=True, max_length=300, verbose_name='Twitter_URL'),
        ),
        migrations.AddField(
            model_name='profile',
            name='face_book',
            field=models.URLField(blank=True, max_length=300, verbose_name='FaceBook_URL'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pref',
            field=models.CharField(blank=True, max_length=5, verbose_name='お住まいの都道府県'),
        ),
    ]
