# Generated by Django 3.1.7 on 2021-03-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210322_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='お電話でのカウンセリングはお電話番号が必須です。', max_length=15, verbose_name='お電話番号'),
        ),
    ]
