# Generated by Django 3.1.7 on 2021-03-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210322_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nick_name',
            field=models.CharField(help_text='カウンセラーにはニックネームが表示されます。', max_length=255, verbose_name='ニックネーム'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='※お電話でのカウンセリングはお電話番号が必要です。', max_length=15, verbose_name='お電話番号'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pref',
            field=models.CharField(blank=True, help_text='※対面でのカウンセリングは都道府県が必要です。', max_length=5, verbose_name='お住まいの都道府県'),
        ),
    ]
