# Generated by Django 3.1.7 on 2021-04-02 11:16

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210327_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='face_image',
            field=stdimage.models.StdImageField(blank=True, default='/static/icon/images.png', upload_to='media/face_image'),
        ),
    ]
