# Generated by Django 3.1.7 on 2021-04-05 13:50

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210405_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='your_image',
            field=stdimage.models.StdImageField(blank=True, default='images.png', upload_to='media/your_image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='face_image',
            field=stdimage.models.StdImageField(blank=True, default='/images.png', upload_to='media/face_image'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='qualification_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='保有資格'),
        ),
    ]
