# Generated by Django 3.1.7 on 2021-04-05 14:37

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210405_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='face_image',
            field=stdimage.models.StdImageField(blank=True, default='/images.png', upload_to='media/face_image', verbose_name='顔写真'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='qualification',
            field=models.ManyToManyField(blank=True, max_length=100, related_name='保持資格', to='accounts.Qualification'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='your_image',
            field=stdimage.models.StdImageField(blank=True, default='images.png', upload_to='media/your_image', verbose_name='あなたのイメージ写真'),
        ),
    ]
