# Generated by Django 3.1.7 on 2021-04-05 18:38

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210405_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='face_image',
            field=stdimage.models.StdImageField(blank=True, upload_to='media/face_image', verbose_name='顔写真'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='your_image',
            field=stdimage.models.StdImageField(blank=True, upload_to='media/your_image', verbose_name='あなたのイメージ写真'),
        ),
    ]
