# Generated by Django 3.1.7 on 2021-04-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210413_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account_no',
            field=models.CharField(max_length=20, verbose_name='口座番号'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_code',
            field=models.CharField(max_length=3, verbose_name='銀行コード'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='branch_office_code',
            field=models.CharField(max_length=5, verbose_name='支店コード'),
        ),
    ]
