# Generated by Django 3.1.7 on 2021-04-07 07:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutlist',
            name='user',
        ),
        migrations.AddField(
            model_name='checkoutlist',
            name='buyer_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='buyer_user', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkoutlist',
            name='vendor_user',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_user', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkoutlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 7, 17, 41, 244858, tzinfo=utc), verbose_name='契約日'),
        ),
    ]
