# Generated by Django 3.1.7 on 2021-04-07 09:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210407_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutlist',
            name='amount',
            field=models.ImageField(default=6000, max_length=200000, upload_to='', verbose_name='料金'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkoutlist',
            name='plan_type',
            field=models.CharField(default='単発', max_length=255, verbose_name='プランタイプ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkoutlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 9, 53, 9, 262726, tzinfo=utc), verbose_name='契約日'),
        ),
    ]
