# Generated by Django 3.1.7 on 2021-04-07 10:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210407_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutlist',
            name='amount',
            field=models.IntegerField(max_length=200000, verbose_name='料金'),
        ),
        migrations.AlterField(
            model_name='checkoutlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 10, 7, 33, 412899, tzinfo=utc), verbose_name='契約日'),
        ),
    ]
