# Generated by Django 3.1.7 on 2021-04-12 05:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20210407_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutlist',
            name='cancel_flag',
            field=models.BooleanField(default=False, verbose_name='cancelフラグ'),
        ),
        migrations.AlterField(
            model_name='checkoutlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 12, 5, 33, 29, 463646, tzinfo=utc), verbose_name='契約日'),
        ),
    ]
