# Generated by Django 3.1.7 on 2021-04-12 09:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20210412_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutlist',
            name='customer_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='stripe顧客ID'),
        ),
        migrations.AlterField(
            model_name='checkoutlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 12, 9, 53, 58, 610090, tzinfo=utc), verbose_name='契約日'),
        ),
    ]
