# Generated by Django 3.1.7 on 2021-04-15 05:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20210412_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutlist',
            old_name='strip_id',
            new_name='stripe_id',
        ),
        migrations.AlterField(
            model_name='checkoutlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 5, 58, 50, 415876, tzinfo=utc), verbose_name='契約日'),
        ),
    ]
