# Generated by Django 3.1.7 on 2021-03-14 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_name', models.CharField(blank=True, max_length=6, null=True)),
                ('pref_code', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StyleChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('catch_message', models.TextField(help_text='ヒント！ご相談される方が最初に見るメッセージです。', max_length=200, verbose_name='アイキャッチメッセージ')),
                ('detail', models.TextField(max_length=1000, verbose_name='本文')),
                ('target', models.CharField(max_length=100, verbose_name='対象者')),
                ('plan_type', models.CharField(choices=[('Single_shot', '単発'), ('Continue', '継続')], max_length=20, verbose_name='プランタイプ')),
                ('price', models.CharField(max_length=10, verbose_name='価格')),
                ('session_time', models.CharField(help_text='ヒント！分でご記入ください', max_length=3, verbose_name='カウンセリング時間/一回')),
                ('counseling_active', models.CharField(choices=[('1', 'すぐに話せます。'), ('2', '本日中にお話ができます。'), ('2', '調整できます。')], max_length=20, verbose_name='カウンセリングのタイミング')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.category')),
                ('pref', models.ManyToManyField(blank=True, related_name='pref', to='plan.Pref')),
                ('style_choices', models.ManyToManyField(related_name='style', to='plan.StyleChoices')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
