# Generated by Django 3.1.7 on 2021-03-08 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_name', models.CharField(blank=True, max_length=6, null=True)),
                ('pref_code', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='タイトル')),
                ('detail', models.TextField(max_length=1000, verbose_name='本文')),
                ('target', models.CharField(max_length=100, verbose_name='対象者')),
                ('plan_type', models.CharField(choices=[('Single_shot', '単発'), ('Continue', '継続')], max_length=20, verbose_name='プランタイプ')),
                ('price', models.CharField(max_length=10, verbose_name='価格')),
                ('counseling_style', models.BooleanField(choices=[('Face_to', '対面'), ('Online', 'オンライン'), ('Phone', 'お電話'), ('Mail', 'お手紙')], default=False, verbose_name='カンセリングスタイル')),
                ('pref', models.CharField(blank=True, max_length=20, verbose_name='カウンセリングエリア')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
