# Generated by Django 3.1.7 on 2021-03-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='counseling_style',
            field=models.CharField(choices=[('Face_to', '対面'), ('Online', 'オンライン'), ('Phone', 'お電話'), ('Mail', 'お手紙')], max_length=10, verbose_name='カンセリングスタイル'),
        ),
    ]
