# Generated by Django 3.1.7 on 2021-03-24 07:06

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_sign',
            field=stdimage.models.StdImageField(blank=True, default='icon/images.png', upload_to='media/plan_sign'),
        ),
    ]
