# Generated by Django 3.1.7 on 2021-03-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_plan_plan_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='release',
            field=models.BooleanField(default=False, verbose_name='公開'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='catch_message',
            field=models.TextField(help_text='ヒント！ご相談される方が最初に見るメッセージです。', max_length=100, verbose_name='アイキャッチメッセージ'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='title',
            field=models.CharField(max_length=30, verbose_name='タイトル'),
        ),
    ]
