# Generated by Django 3.1.7 on 2021-03-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20210308_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='catch_message',
            field=models.CharField(default=1, max_length=200, verbose_name='アイキャッチメッセージ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='title',
            field=models.CharField(max_length=100, verbose_name='タイトル'),
        ),
    ]
