# Generated by Django 3.1.7 on 2021-03-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_auto_20210308_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='catch_message',
            field=models.CharField(default='最初に見るメッセージです。', max_length=200, verbose_name='アイキャッチメッセージ'),
        ),
    ]
