# Generated by Django 3.1.7 on 2021-03-26 03:11

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_auto_20210324_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_sign',
            field=stdimage.models.StdImageField(blank=True, default='static/icon/MeAnd_Logo1.png', upload_to='media/plan_sign'),
        ),
    ]
