# Generated by Django 3.1.7 on 2021-03-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_auto_20210308_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='counseling_active',
            field=models.CharField(choices=[('1', 'すぐに話せます。'), ('2', '本日中にお話ができます。'), ('2', '調整できます。')], default=1, max_length=20, verbose_name='カウンセリングのタイミング'),
            preserve_default=False,
        ),
    ]
