# Generated by Django 3.1.7 on 2021-03-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_plan_counseling_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='session_time',
            field=models.CharField(default=45, help_text='分でご記入ください', max_length=3, verbose_name='カウンセリング時間/一回'),
            preserve_default=False,
        ),
    ]
