# Generated by Django 3.1.7 on 2021-04-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_remove_plan_style_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='style_choices',
            field=models.ManyToManyField(related_name='style', to='plan.StyleChoices'),
        ),
    ]
