# Generated by Django 3.1.7 on 2021-03-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_plan_session_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='catch_message',
            field=models.TextField(help_text='ヒント！ご相談される方が最初に見るメッセージです。', max_length=200, verbose_name='アイキャッチメッセージ'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='session_time',
            field=models.CharField(help_text='ヒント！分でご記入ください', max_length=3, verbose_name='カウンセリング時間/一回'),
        ),
    ]
