# Generated by Django 3.1.7 on 2021-03-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_auto_20210310_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='plan',
            name='counseling_style',
        ),
        migrations.AddField(
            model_name='plan',
            name='style_choices',
            field=models.ManyToManyField(related_name='style', to='plan.StyleChoices'),
        ),
    ]
