# Generated by Django 3.1.7 on 2021-03-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_auto_20210310_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='pref',
        ),
        migrations.AddField(
            model_name='plan',
            name='pref',
            field=models.ManyToManyField(blank=True, related_name='pref', to='plan.Pref'),
        ),
    ]
