# Generated by Django 3.1.7 on 2021-04-22 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='city',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='plan.pref'),
            preserve_default=False,
        ),
    ]
