# Generated by Django 3.1.7 on 2021-04-22 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0009_plan_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='city',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='plan.city'),
        ),
        migrations.RemoveField(
            model_name='plan',
            name='pref',
        ),
        migrations.AddField(
            model_name='plan',
            name='pref',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='plan.pref'),
            preserve_default=False,
        ),
    ]
