# Generated by Django 3.1.7 on 2021-04-28 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0010_auto_20210422_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plan.city'),
        ),
    ]
