# Generated by Django 3.1.7 on 2021-03-16 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
        ('reservation', '0002_auto_20210315_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.plan', verbose_name='to_staff'),
        ),
    ]
