# Generated by Django 3.1.7 on 2021-03-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20210317_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='plan',
        ),
    ]
