# Generated by Django 3.1.7 on 2021-03-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_reservationmessage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmessage',
            name='message',
            field=models.TextField(max_length=500, verbose_name='メッセージ'),
        ),
    ]
