# Generated by Django 3.1.7 on 2021-03-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_auto_20210319_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, choices=[('1', '日程調整中'), ('2', '日程調整完了'), ('3', 'カンセリング完了'), ('4', 'キャンセル')], max_length=20, verbose_name='ステータス'),
        ),
    ]
