# Generated by Django 3.1.7 on 2021-03-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='active',
            field=models.BooleanField(default=False, verbose_name='稼働可否'),
        ),
    ]
