# Generated by Django 3.1.7 on 2021-03-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
        ('reservation', '0010_auto_20210320_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='style_choice',
            field=models.ManyToManyField(related_name='reserve_style_choice', to='plan.StyleChoices'),
        ),
    ]
