# Generated by Django 3.1.7 on 2021-03-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_auto_20210326_1211'),
        ('reservation', '0011_reservation_style_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='style_choice',
            field=models.ManyToManyField(related_name='reserve_style_choice', to='plan.StyleChoices', verbose_name='面談スタイル'),
        ),
    ]
