# Generated by Django 3.1.7 on 2021-04-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_auto_20210327_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='stripe_id'),
        ),
    ]
